# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.IntegerField(choices=[(1, b'Phone Interview'), (2, b'In Person Interview')])),
                ('stage', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=128, null=True)),
                ('notes', models.TextField(null=True)),
                ('outcome', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('benefits', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('date_added', models.DateTimeField()),
                ('listing', models.URLField(max_length=1024, null=True)),
                ('notes', models.TextField(null=True)),
                ('location', models.CharField(max_length=128, null=True)),
                ('referral', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plutus_core.Opportunity'),
        ),
        migrations.AddField(
            model_name='interview',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plutus_core.Opportunity'),
        ),
    ]
